# config/packages/lexik_jwt_authentication.yaml
lexik_jwt_authentication:
    secret_key:    '%env(resolve:JWT_SECRET_KEY)%'
    public_key:    '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase:   '%env(JWT_PASSPHRASE)%'
    token_ttl:     3600

    # Ось воно! Тепер в payload буде ключ "email" => значення getUserIdentifier()
    user_id_claim: email

    token_extractors:
        authorization_header: true
        query_parameter:     true
        cookie:
            enabled: true
            name:    'JWT'
