framework:
    rate_limiter:
        login:
            policy: 'token_bucket'
            limit: 5
            rate: { interval: '1 minute', amount: 5 }

        api:
            policy: 'token_bucket'
            limit: 100
            rate: { interval: '1 minute', amount: 60 }

        protected_api:
            policy: 'token_bucket'
            limit: 30
            rate: { interval: '1 minute', amount: 30 }
