# This file configures rate limiting for the application
# Rate limiting prevents abuse by limiting how many requests can be made in a given time period
framework:
    rate_limiter:
        # Login rate limiter - protects against brute force attacks
        # Allows only 5 login attempts per minute
        login:
            policy: 'token_bucket'  # Algorithm used for rate limiting
            limit: 5                # Maximum number of tokens (requests allowed)
            rate: { interval: '1 minute', amount: 5 }  # Refill rate: 5 tokens per minute

        # General API rate limiter - for standard endpoints
        # Allows up to 100 requests with 60 requests refilled per minute
        api:
            policy: 'token_bucket'
            limit: 100              # Maximum bucket capacity
            rate: { interval: '1 minute', amount: 60 }  # Refill rate: 60 tokens per minute

        # Protected API rate limiter - for sensitive endpoints
        # More restrictive: only 30 requests per minute
        protected_api:
            policy: 'token_bucket'
            limit: 30               # Maximum bucket capacity
            rate: { interval: '1 minute', amount: 30 }  # Refill rate: 30 tokens per minute
