# config/services.yaml
parameters:
    # Parameters can be added here as needed

services:
    _defaults:
        autowire:      true
        autoconfigure: true
        public:        false

        # Service bindings can be added here as needed
        bind:
            # Add service bindings here if needed

    # всі контролери мають бути публічними і з тегом controller.service_arguments
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        public: true

    # Решта ваших автосервісів
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
